### ISSUE TITLE
Container-to-container hostname lookup

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kanto/container-management#114]
When two containers want to communicate with each other (e.g. an application using a service), the service's port needs to be exposed to the host. There does not seem to be any kind of container-to-container communication possible by using service names or mapped hostnames.

It would be nice to have an indirect mapping of container names (or service names) to a specific container in the network, like this:

- Deploy service as container 1 with name `myservice`
- Configure application in container 2 to connect to `myservice:55555`

Pro: It's easy to configure for the application and service deployer. No host ports need to be reserved and no services are exposed on the host network interface, if not necessary.

Contra: The names of the containers become part of the requirements and may not be changed arbitrarily any more.

Our current workaround is this:

- Deploy service as container 1, name of container is irrelevant
- Add port mapping and expose the port of the service to the host, e.g. `container:55555 -> host:30555`
- Add extra_hosts entry `myservice:host_ip` to the application container 2
- Configure application in container 2 to connect to `myservice:30555`
- Both using same bridge network

Ideas on implementations (just to spark the discussion):

- Custom DNS service for containers to resolve container / service names to the respective bridge network ip address of the target container. This is how k3s is doing it and is also flexible at runtime, eg additional containers can be added and discovered at runtime.
- Allow the extra_hosts entries to contain other mappings, not only `host_ip`. Eg a mapping like `service:myservice` where `service` is the hostname used by the client application and `myservice` is the container name of the target service.
- Use a "globally" shared hosts file, eg adding all the container hostnames to the same shared hosts file, separated per bridge network.

Right now, the special feature that a inside of the container, there is a hostname entry auto-generated with `<containername>-host` is only visible inside of the container. Unfortunately, that is not sufficient for communication between containers.

- https://github.com/eclipse-kanto/container-management/issues/122
- https://github.com/eclipse-kanto/kanto/issues/197

**Comment by k-gostev** [comment]
Thank you @mikehaller for this proposal, I see that this feature could indeed be beneficial.
I have made some initial investigations regarding the implementation proposals:

## Container-to-container hostname lookup

1. Custom DNS service
   1. Using CoreDNS plugin (k3s like approach) - This option seems applicable in our scenario. The CoreDNS binary is only ~14.5MB, so if the Kanto user wants additional DNS service solution it can fit on the edge device. The benefit of it would be also that it can be used with other plugins and scenarios. This approach will be intuitive for the k3s and k8s users. The downside of this approach is that it will bring more dependencies to the overall setup. Another container property should be introduced to tell the DNS service which container hostname can be resolvable and which not, to make the configuration more versatile. From what I see, we will also have to contribute this plugin to the CoreDNS project, which has its ups and downs. Another possible option is to use id from a private fork, but I am a bit reserved about that. One question that should be asked considering this approach is "Would that be an overkill, in the context of Kanto CM?"
   2. Writing internal DNS resolver - Implementation wise this looks like to be kind of the same as the CoreDNS plugin, plus the UDP communication layer, however I am sure that this is not the case, because building a DNS server is not that trivial and inside the container manager I am sure that it will bring more negatives than positives, so my suggestion is to avoid this option.

2. Allow the extra_hosts entries to contain other mappings:
   - There are a couple of things that needs to be considered with this approach.
      1. This kind of mapping will be easy to achieve from the libnetwork service as it has access to all necessary resources (containers, host files, network, etc.).
      2. If you delete a container, and then create one that would have the same hostname it could be assigned with another IP in some cases.
      3. Different IP could be assigned to the same container when the container-management service is restarted.
      4. Considering points 2. and 3. I think that the best approach of dealing with those issues is to create a task that will monitor the containers and refreshes their hosts files constantly.
      5. Even with 4. implemented there is still a chance for incorrect service to IP resolution, due to concurrent events, but assume that this can't be avoided with `Custom DNS service either`

3. Use a "globally" shared hosts file
   -    Everything from point 2. is valid here as well, plus the additional maintenance of another file. I also think that the configuration wise option 2. is more intuitive. Also, IMO one hosts file for all (or some) containers could be bring a bit of a mess.

Considering the above I think option 2. will be a suitable approach, as it will be the most lightweight approach and will step on already existing implementations utilizing the libnetwork service. IMO there no need for using CoreDNS, or at least I can't justify it. Of course I am open to suggestions and comments.

**Comment by mikehaller** [comment]
I too think that a full-blown DNS service may not be necessary and focusing on the container service discovery aspect may have the best trade-off regarding cost/benefit.

Being able to manage the extra_hosts and somehow define the mapping of the internally mapped hostnames to the IP addresses of other containers is enough for this use case.

**Comment by k-gostev** [comment]
The feature is implemented and documented as discussed here.
