### ISSUE TITLE
snapshots occupies too much space after many hard-resets

### ISSUE THREAD

**Issue by pichumanichellappa** [eclipse-kanto/container-management#139]
We are having a python app, running based on eclipse velocitas(https://github.com/eclipse-velocitas/vehicle-app-python-template).

We encounter a problem when we do many hard-reboots. each time when we do a reboot approximately 40 MB more space is taken away from the system. The system is ending up with no space left in a duration of time(2-3 days approximately).

We had investigated, snapshots of the conatinerd/kanto-cm occupies more space every time after a reboot is done.

**Comment by k-gostev** [comment]
Hi, after you reproduce the issue please provide some additional information in order to ease the investigation:
- Container management config `/etc/container-management/config.json`
- Containerd config `/etc/containerd/config.toml`
- The contained snapshots list `ctr -n kanto-cm snapshots ls`
- Tree structure of tmp (or whatever directory is used by `staticx` which potentially triggers the creation of snapshots   `/var/lib/container-management/overlayfs/<container-id>/rootfs/tmp/`

**Comment by tobiwan3** [comment]
@k-gostev thank you for the analysis. I had suspected that to be an possibility. Does kanto support volume quotas per container? I did not find anything in https://websites.eclipseprojects.io/kanto/docs/references/containers/.

**Comment by k-gostev** [comment]
The documentation is up to date, so all features are listed there. I think @pichumanichellappa is currently figuring out a way to mount a directory on a `tmpfs` filesystem for the tmp files, which would be a good solution to this issue IMO.

**Comment by k-gostev** [comment]
As there not any any further questions I am closing this issue. Please reopen it if you need further assistance.
