### ISSUE TITLE
Clear out container configuration inconsistances 

### ISSUE THREAD

**Issue by dimitar-dimitrow** [eclipse-kanto/container-management#58]
Containers could be created via different interfaces. However, some configurations are missing in some of them, e.g. network mode configuration is missing when a container is created via ContainerFactory feature, as described in #55. The target is to clear such inconsistencies and provide clearer documentation about this topic.

**Tasks:**
* #69
* eclipse-kanto/kanto#149

**Comment by MilenaJaentgen** [comment]
Thank you for your help in issue [#55](https://github.com/eclipse-kanto/container-management/issues/55)! Here you described a way to configure a container by using the SoftwareUpdatable feature of the edge:containers device. For that one has to provide a config.json file as artifact. 

In my understanding the config.json file must be reachable from a server with protocols HTTP, HTTPS, FTP or SFTP. Otherwise one can not provide an "url" in the "download" part of the artifact. 

Is this right or is there another possibility to make the config.json file reachable within the container management of Eclipse Kanto?

**Comment by k-gostev** [comment]
I will start working on this, so please assign me ass well.
