### ISSUE TITLE
Signed images support

### ISSUE THREAD

**Issue by ttttodorov** [eclipse-kanto/container-management#59]
Making sure a solution works with trusted container images is an important security aspect that has to be covered by any container management solution.

Different projects have already addressed the issue:
* [moby](https://mobyproject.org/projects/)'s with [Notary](https://github.com/notaryproject/notary) - obsolete v1 supported and integrated by Docker, v2 - to be scheduled for a future release if/when stable
* [sigstore](https://www.sigstore.dev/)'s [Cosign](https://github.com/sigstore/cosign) - production-ready supported and integrated by different RedHat solutions

Based on the possible options and their status, Cosign can be integrated as a first step to enhance the security of the Kanto container management component for signed images support and verification.

**Tasks:**
* eclipse-kanto/container-management#92
* eclipse-kanto/container-management#67 
* eclipse-kanto/container-management#130
* eclipse-kanto/container-management#97
* eclipse-kanto/container-management#91
* eclipse-kanto/kanto#150

**Comment by dimitar-dimitrow** [comment]
As this task was delayed in time, here is an update for the current container image signing perspective. While the OCI image spec does not have an official 1.1.0 release, it is on its [fifth release candidate](https://github.com/opencontainers/image-spec/tree/v1.1.0-rc5) and official [1.1.0](https://github.com/opencontainers/image-spec/milestone/14) version is expected soon. The main feature in OCI image spec 1.1.0 is to natively store, discover, and pull a graph of content(signatures, SBoM  and etc.) associated with specific container images in a registry. The [notary/notation-go(aka notary v2)](https://github.com/notaryproject/notation-go) is a library that supports Notation sign, verify, push, pull of OCI artifacts, which adopts the 1.1.0 OCI image spec.

Kanto Container Management must adhere to OCI spec and provide signed image verification using notary instead of cosign.
