### ISSUE TITLE
Provide integration tests for the CLI capabilities

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/container-management#64]
The container management component can be controlled locally via its `kanto-cm` CLI tooling, thus, it can have local tests run without going through any server instances. By using `kanto-cm` to manage available containers, the tests must ensure the container management portions themselves function correctly.

**Comment by k-gostev** [comment]
Some initial thoughts on the implementation specifics:
### CLI Commands execution 

- Instead of building en executable the CLI commands can be executed from the test using `go run containerm/cli <command>`. This way building and maintaining binaries can be avoided.
- The test can be executed using the `--host` flag that points to exposed for testing purposes CM service once #83 and #84 are resolved. 
- The test can be executed with every PR if the above conditions are met.
 

### Assertions

- The return result of `kanto-cm create` as well as all other commands must be 0.
- The output string of `kanto-cm create` should be > 0.
- `kanto-cm get` should use the output string of `kanto-cm create` and the result must be a valid `json`.
- The output of `kanto-cm list` must be > 0 and should contain the ID of the container created with the first command.
- `kanto-cm rename` must be validated by calling `kanto-cm get` and checking if the container is with the desired new name.
- `kanto-cm start` and `kanto-cm start` must be validated by calling `kanto-cm get` and checking the container's status.
- The output string og `kanto-cm sysinfo` and `kanto-cm help` should be > 0 or not validated at all.
- `kanto-cm update` must be validated by calling `kanto-cm get` and checking if the container is updated.
- `kanto-cm remove` must be called at the end of testing process to clean up the environment.

**Comment by e-grigorov** [comment]
- building test executable provides more flexibility, there is no need to have Go tooling on the test environment
- `The test can be executed using the --host flag` - it's an integration test with e2e scenarios i.e. `kanto-cm` should be tested as it's provided by the container management
- about the assertions, they should be able to validate all command messages i.e. with valid/invalid parameters, even the command help message can be asserted
